import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider"
import { ToggleTheme } from "@/components/theme/toggle-theme";
import { UserButton } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="p-3 border-b-2">
              <nav className="flex flex-wrap flex-row justify-between">
                <div className="text-2xl font-extrabold uppercase">
                  Pwd Manager
                </div>
                <div className="flex flex-wrap flex-row justify-end gap-5 ">
                  <ToggleTheme />
                  <UserButton />
                </div>
              </nav>
            </div>

            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
